<?php
/**
 * Created by PhpStorm.
 * User: pnguyen
 * Date: 7/16/15
 * Time: 12:00 PM
 */

function usgs_generate_paginator($page = NULL,$page_size = NULL,$total = NULL,$params = []){

  if(is_null($page) or is_null($page_size) or is_null($total))
    return "";

  global $base_url;

  $html = "<ul class='pagination'>";

  // Total amount of pages
  $pages = ceil($total / $page_size);

  // Return empty string if out of bounds
  if($page == 0 or $page > $pages or $pages <= 1)
    return "";

  // Get the url alias for href
  $node_page = menu_get_item()['href'];

  foreach(menu_get_item()['theme_arguments'] as $theme_arg)
    $node_page .= "/" . $theme_arg;

  $node_page = drupal_get_path_alias($node_page);

  // Contains the params to pass along with page
  $paramStr = "";

  foreach((array)$params as $key => $param)
    $paramStr .= "&{$key}={$param}";

  $prev = "<li><a href='{$base_url}/{$node_page}?page=" . ($page - 1) . $paramStr . "'>prev</a></li>";
  $next = "<li><a href='{$base_url}/{$node_page}?page=" . ($page + 1) . $paramStr . "'>next</a></li>";

  if($page > 1)
    $html .= $prev;

  if($page < 3)
    $page_range = range(1,5);
  else if($page > ($pages - 5))
    $page_range = range($pages - 4, $pages);
  else
    $page_range = range($page - 2, $page + 2);

  foreach($page_range as $pagenum){

    $active = "";

    if($pagenum == $page)
      $active = "class='active'";

    if($pagenum > 0 and $pagenum <= $pages)
      $html .= "<li {$active}><a href='{$base_url}/{$node_page}?page=" . $pagenum . $paramStr . "'>{$pagenum}</a></li>";
  }

  if($page < $pages)
    $html .= $next;

  $html .= "</ul>";

  return $html;
}
