<?php

/**
 *
 * Implement hook_ctools_plugin_directory().
 *
 * @param $module
 * @param $plugin
 * @return string
 */
function usgs_multimedia_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'content_types') {
    return "plugins/" . $plugin;
  }
}

function usgs_multimedia_views_api(){
  return [
    'api' => 3,
  ];
}

/**
 * Implementation of hook_preprocess().
 */
function usgs_multimedia_preprocess_usgs_layout_1(&$vars) {
  module_load_include('inc', 'usgs_multimedia', 'plugins/content_types/usgs_mm_section');

  $view = usgs_mm_tab_render(NULL, NULL, NULL, NULL);
  $vars['mm'] = $view->content;
}